/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CommunityMemberRole;

import business.Enterprise.Enterprise;
import business.Organization.HouseholdOrg;
import business.Organization.Organization;
import business.Person.Person;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userInterface.DistrictAdminRole.AddNeighborhoodJPanel;

/**
 *
 * @author Reshmi
 */
public class CommunityMemberWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private HouseholdOrg householdOrg;
    private Person person;
    public CommunityMemberWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,Enterprise enterprise,Organization org) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.householdOrg = (HouseholdOrg)org;
        person = userAccount.getPerson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mngPersonProfileBtn = new javax.swing.JButton();
        mngEnergyConsumptionBtn = new javax.swing.JButton();
        viewVitalSignBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        viewVitalSignAlertsBtn = new javax.swing.JButton();
        viewEnergyConsumptionAlertsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        mngPersonProfileBtn.setBackground(new java.awt.Color(0, 153, 0));
        mngPersonProfileBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        mngPersonProfileBtn.setForeground(new java.awt.Color(255, 255, 255));
        mngPersonProfileBtn.setText("MANAGE PERSON PROFILE");
        mngPersonProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngPersonProfileBtnActionPerformed(evt);
            }
        });

        mngEnergyConsumptionBtn.setBackground(new java.awt.Color(0, 153, 0));
        mngEnergyConsumptionBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        mngEnergyConsumptionBtn.setForeground(new java.awt.Color(255, 255, 255));
        mngEnergyConsumptionBtn.setText("MANAGE ENERGY CONSUMPTIONS");
        mngEnergyConsumptionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngEnergyConsumptionBtnActionPerformed(evt);
            }
        });

        viewVitalSignBtn.setBackground(new java.awt.Color(0, 153, 0));
        viewVitalSignBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        viewVitalSignBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewVitalSignBtn.setText("MANAGE VITAL SIGNS");
        viewVitalSignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVitalSignBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/CommunityMemberRole/eco-house-concept-green-energy-icons.jpg"))); // NOI18N

        viewVitalSignAlertsBtn.setBackground(new java.awt.Color(0, 153, 0));
        viewVitalSignAlertsBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        viewVitalSignAlertsBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewVitalSignAlertsBtn.setText("MEDICAL ALERTS");
        viewVitalSignAlertsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVitalSignAlertsBtnActionPerformed(evt);
            }
        });

        viewEnergyConsumptionAlertsBtn.setBackground(new java.awt.Color(0, 153, 0));
        viewEnergyConsumptionAlertsBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        viewEnergyConsumptionAlertsBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewEnergyConsumptionAlertsBtn.setText("ENERGY CONSUMPTION ALERTS");
        viewEnergyConsumptionAlertsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEnergyConsumptionAlertsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mngEnergyConsumptionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewVitalSignBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mngPersonProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewVitalSignAlertsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewEnergyConsumptionAlertsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mngPersonProfileBtn)
                .addGap(18, 18, 18)
                .addComponent(viewVitalSignBtn)
                .addGap(18, 18, 18)
                .addComponent(mngEnergyConsumptionBtn)
                .addGap(18, 18, 18)
                .addComponent(viewVitalSignAlertsBtn)
                .addGap(18, 18, 18)
                .addComponent(viewEnergyConsumptionAlertsBtn)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mngPersonProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngPersonProfileBtnActionPerformed
        ManagePersonProfileJPanel mngPersonProfileJPanel = new ManagePersonProfileJPanel(userProcessContainer,person);
        userProcessContainer.add("managePersonProfileJPanel", mngPersonProfileJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngPersonProfileBtnActionPerformed

    private void mngEnergyConsumptionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngEnergyConsumptionBtnActionPerformed
        // TODO add your handling code here:
        ManageEnergyConsumptionJPanel mngEnergyConsumptionJPanel = new ManageEnergyConsumptionJPanel(userProcessContainer,person);
        userProcessContainer.add("manageEnergyConsumptionJPanel", mngEnergyConsumptionJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngEnergyConsumptionBtnActionPerformed

    private void viewVitalSignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVitalSignBtnActionPerformed
        // TODO add your handling code here:
        ManageVitalSignsJPanel viewVitalSignJPanel = new ManageVitalSignsJPanel(userProcessContainer,person);
        userProcessContainer.add("viewVitalSignJPanel", viewVitalSignJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewVitalSignBtnActionPerformed

    private void viewVitalSignAlertsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVitalSignAlertsBtnActionPerformed
        ViewVitalSignAlertsJPanel viewVSAlertsJPanel = new ViewVitalSignAlertsJPanel(userProcessContainer,userAccount,enterprise,householdOrg);
        userProcessContainer.add("viewVSAlertsJPanel", viewVSAlertsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewVitalSignAlertsBtnActionPerformed

    private void viewEnergyConsumptionAlertsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEnergyConsumptionAlertsBtnActionPerformed
        ViewEnergyConsumptionAlerts viewECAlertsJPanel = new ViewEnergyConsumptionAlerts(userProcessContainer,userAccount,enterprise,householdOrg);
        userProcessContainer.add("viewECAlertsJPanel", viewECAlertsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewEnergyConsumptionAlertsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mngEnergyConsumptionBtn;
    private javax.swing.JButton mngPersonProfileBtn;
    private javax.swing.JButton viewEnergyConsumptionAlertsBtn;
    private javax.swing.JButton viewVitalSignAlertsBtn;
    private javax.swing.JButton viewVitalSignBtn;
    // End of variables declaration//GEN-END:variables
}
