/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.HospitalAdminRole;

import business.Enterprise.Enterprise;
import business.Organization.HospitalAdminOrg;
import business.Organization.HouseholdOrg;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Reshmi
 */
public class HospitalAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    //private PersonDirectory personDir;
    //private HouseholdOrg houseOrg;
    private HospitalAdminOrg hospitalOrg;
    private UserAccount userAccount;
    private Enterprise enterprise;
    public HospitalAdminWorkAreaJPanel(JPanel userProcessContainer,Enterprise enterprise,HospitalAdminOrg hospitalOrg,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        //this.personDir = personDir;
        this.hospitalOrg = hospitalOrg;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mngPatientBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        mngPatientBtn.setBackground(new java.awt.Color(0, 153, 0));
        mngPatientBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        mngPatientBtn.setForeground(new java.awt.Color(255, 255, 255));
        mngPatientBtn.setText("MANAGE PATIENTS  RECORDS");
        mngPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngPatientBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/HospitalAdminRole/hospital_icon.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(mngPatientBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1)))
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(mngPatientBtn)
                .addGap(117, 117, 117))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mngPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngPatientBtnActionPerformed
        Organization org = null;
        for(Organization organization:enterprise.getOrganizationList().getOrganizationList()){
            if(organization instanceof HouseholdOrg){
                org = organization;
            }
        }
        ManagePatientsJPanel mngPatientJPanel = new ManagePatientsJPanel(userProcessContainer, (HouseholdOrg)org,userAccount,enterprise);
        userProcessContainer.add("managePatientJPanel", mngPatientJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngPatientBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mngPatientBtn;
    // End of variables declaration//GEN-END:variables
}
