/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.DistrictAdminRole;

import business.EcoDistrict;
import business.Neighborhood.Neighborhood;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reshmi
 */
public class AddNeighborhoodJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNeighborhoodJPanel
     */
    private JPanel userProcessContainer;
    private EcoDistrict ecoDistrict;
    public AddNeighborhoodJPanel(JPanel userProcessContainer,EcoDistrict ecoDistrict) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoDistrict = ecoDistrict;
        populateNeighborhoodTable();
    }

    public void populateNeighborhoodTable()
    {
        DefaultTableModel model = (DefaultTableModel) neighborhoodAreasTable.getModel();

        model.setRowCount(0);
        for (Neighborhood neighborhood : ecoDistrict.getNeighborhoodList()) {
            Object[] row = new Object[1];
            row[0] = neighborhood.getNeighborhoodName();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        neighborhoodAreasTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        areaNameTxt = new javax.swing.JTextField();
        addAreasBtn = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        neighborhoodAreasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Neighborhood Areas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(neighborhoodAreasTable);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setText("Area Name");

        addAreasBtn.setBackground(new java.awt.Color(0, 153, 0));
        addAreasBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        addAreasBtn.setForeground(new java.awt.Color(255, 255, 255));
        addAreasBtn.setText("ADD");
        addAreasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAreasBtnActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(0, 153, 0));
        backJButton.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/DistrictAdminRole/smart_areas.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(backJButton))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addAreasBtn)
                            .addComponent(areaNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(addAreasBtn))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DistrictAdminWorkAreaJPanel sysAdminwjp = (DistrictAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addAreasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAreasBtnActionPerformed
        // TODO add your handling code here:
        String areaName = areaNameTxt.getText();
        for(Neighborhood neighborhood: ecoDistrict.getNeighborhoodList()){
        if(neighborhood.getNeighborhoodName().equalsIgnoreCase(areaName)){
          JOptionPane.showMessageDialog(null, "Neighborhood already exists","Warning",JOptionPane.WARNING_MESSAGE);
         
            return;   
        }}
         if(areaName == null || areaName.trim().equals("")){
             JOptionPane.showMessageDialog(null, "Kindly enter the area name!","Warning",JOptionPane.WARNING_MESSAGE);
         
            return;
        }
         else{
              Neighborhood neighborhood = ecoDistrict.createAddNeighborhoods();
            neighborhood.setNeighborhoodName(areaName);
            populateNeighborhoodTable();  
            JOptionPane.showMessageDialog(null, "Neighborhood is added!", "New Area", JOptionPane.INFORMATION_MESSAGE);
       
         }
        areaNameTxt.setText("");
    }//GEN-LAST:event_addAreasBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAreasBtn;
    private javax.swing.JTextField areaNameTxt;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable neighborhoodAreasTable;
    // End of variables declaration//GEN-END:variables
}
