/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.DistrictAdminRole;

import business.EcoDistrict;
import business.Enterprise.Enterprise;
import business.Neighborhood.Neighborhood;
import business.Organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Reshmi
 */
public class DistrictAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DistrictAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoDistrict ecoDistrict;
    public DistrictAdminWorkAreaJPanel(JPanel userProcessContainer,EcoDistrict ecoDistrict) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoDistrict = ecoDistrict;
        populateTree();
    }

    public void populateTree()
    {
        DefaultTreeModel model = (DefaultTreeModel)jTree.getModel();
        ArrayList<Neighborhood> neighborhoodList = ecoDistrict.getNeighborhoodList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        Neighborhood neighborhood;
        Enterprise enterprise;
        Organization organization;

        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);

        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        for (int i = 0; i < neighborhoodList.size(); i++) {
            neighborhood = neighborhoodList.get(i);
            networkNode = new DefaultMutableTreeNode(neighborhood.getNeighborhoodName());
            networks.insert(networkNode, i);

            enterpriseList = neighborhood.getEnterpriseList().getEnterpriseList();

            for (int j = 0; j < enterpriseList.size(); j++) {
                enterprise = enterpriseList.get(j);
                enterpriseNode = new DefaultMutableTreeNode(enterprise.getOrgName());
                networkNode.insert(enterpriseNode, j);

                organizationList = enterprise.getOrganizationList().getOrganizationList();
                for (int k = 0; k < organizationList.size(); k++) {
                    organization = organizationList.get(k);
                    organizationNode = new DefaultMutableTreeNode(organization.getOrgName());
                    enterpriseNode.insert(organizationNode, k);
                }
            }
        }

        model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        mngNeighborhoodAdminBtn = new javax.swing.JButton();
        addNeighborhoodBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        monitorAreasBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("EcoDistrict");
        jTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        mngNeighborhoodAdminBtn.setBackground(new java.awt.Color(0, 153, 0));
        mngNeighborhoodAdminBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        mngNeighborhoodAdminBtn.setForeground(new java.awt.Color(255, 255, 255));
        mngNeighborhoodAdminBtn.setText("MANAGE ADMINS");
        mngNeighborhoodAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngNeighborhoodAdminBtnActionPerformed(evt);
            }
        });

        addNeighborhoodBtn.setBackground(new java.awt.Color(0, 153, 0));
        addNeighborhoodBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        addNeighborhoodBtn.setForeground(new java.awt.Color(255, 255, 255));
        addNeighborhoodBtn.setText("ADD NEIGHBORHOOD");
        addNeighborhoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNeighborhoodBtnActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/DistrictAdminRole/smart-city-visual.jpg"))); // NOI18N

        monitorAreasBtn.setBackground(new java.awt.Color(0, 153, 0));
        monitorAreasBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        monitorAreasBtn.setForeground(new java.awt.Color(255, 255, 255));
        monitorAreasBtn.setText("MONITOR NEIGHBORHOOD AREAS");
        monitorAreasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitorAreasBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addNeighborhoodBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(monitorAreasBtn)
                            .addComponent(mngNeighborhoodAdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(addNeighborhoodBtn))
                .addGap(18, 18, 18)
                .addComponent(mngNeighborhoodAdminBtn)
                .addGap(18, 18, 18)
                .addComponent(monitorAreasBtn)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addNeighborhoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNeighborhoodBtnActionPerformed
        // TODO add your handling code here:
        AddNeighborhoodJPanel addNeighborhoodJPanel = new AddNeighborhoodJPanel(userProcessContainer, ecoDistrict);
        userProcessContainer.add("manageNeighborhoodJPanel", addNeighborhoodJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addNeighborhoodBtnActionPerformed

    private void mngNeighborhoodAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngNeighborhoodAdminBtnActionPerformed
        // TODO add your handling code here:
        ManageNeighborhoodAdminsJPanel mngNeighborhoodAdminsJPanel = new ManageNeighborhoodAdminsJPanel(userProcessContainer, ecoDistrict);
        userProcessContainer.add("manageAdminsJPanel", mngNeighborhoodAdminsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngNeighborhoodAdminBtnActionPerformed

    private void monitorAreasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitorAreasBtnActionPerformed
        MonitorNeighborhoodAreasJPanel monitorAreasJPanel = new MonitorNeighborhoodAreasJPanel(userProcessContainer, ecoDistrict);
        userProcessContainer.add("monitorAreasJPanel", monitorAreasJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_monitorAreasBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNeighborhoodBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree;
    private javax.swing.JButton mngNeighborhoodAdminBtn;
    private javax.swing.JButton monitorAreasBtn;
    // End of variables declaration//GEN-END:variables
}
