/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.EnterpriseAdmin;

import business.Enterprise.Enterprise;
import business.Organization.EnergyResourceOrg;
import business.Organization.GreenGasTrackingOrg;
import business.Organization.HospitalAdminOrg;
import business.Organization.HospitalDoctorOrg;
import business.Organization.HouseholdOrg;
import business.Organization.Organization;
import business.Organization.Organization.OrganizationType;
import business.Organization.OrganizationDirectory;
import business.Organization.PollutionBoardOrg;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reshmi
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrganizationsJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private OrganizationDirectory orgDir;
    public ManageOrganizationJPanel(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populateTable();
        populateComboBox();
    }

    private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) organizationTable.getModel();
        
        model.setRowCount(0);
        if(enterprise.getOrganizationList().getOrganizationList()!=null){
        for (Organization organization : enterprise.getOrganizationList().getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrgID();
            row[1] = organization.getOrgName();
            
            model.addRow(row);
        }
        }
    }
    
    private void populateComboBox()
    {
        orgTypeComboBox.removeAllItems();
        if(enterprise.getEnterpriseType().getValue().equals("Community")){
//            if(enterprise.getOrganizationList().getOrganizationList()==null){
            for (Organization.OrganizationType type : Organization.OrganizationType.values()){
            if (!(type.getValue().equals(Organization.OrganizationType.DISTRICT_MONITORING_ORG.getValue())||
                    type.getValue().equals(Organization.OrganizationType.POLLUTION_BOARD_ORG.getValue())||
                    type.getValue().equals(Organization.OrganizationType.GREEN_GAS_TRACKING_ORG.getValue())))
                orgTypeComboBox.addItem(type);
            }
//        }
//            else{
//                for(Organization org : enterprise.getOrganizationList().getOrganizationList()){
//                    System.out.println(org.getOrgName());
//                }
//            }
        }
        else{
        for (Organization.OrganizationType type : Organization.OrganizationType.values()){
            if (type.getValue().equals(Organization.OrganizationType.POLLUTION_BOARD_ORG.getValue())||
                    type.getValue().equals(Organization.OrganizationType.GREEN_GAS_TRACKING_ORG.getValue()))
                orgTypeComboBox.addItem(type);
        }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        orgTypeComboBox = new javax.swing.JComboBox();
        addOrgBtn = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        organizationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Organization ID", "Organization Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationTable);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setText("Organization Name");

        orgTypeComboBox.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        orgTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addOrgBtn.setBackground(new java.awt.Color(0, 153, 0));
        addOrgBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        addOrgBtn.setForeground(new java.awt.Color(255, 255, 255));
        addOrgBtn.setText("ADD");
        addOrgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrgBtnActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(0, 153, 0));
        backJButton.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/EnterpriseAdmin/community1.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(backJButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orgTypeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addOrgBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(orgTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backJButton)
                            .addComponent(addOrgBtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addOrgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrgBtnActionPerformed
    Organization.OrganizationType type = (Organization.OrganizationType) orgTypeComboBox.getSelectedItem();
        for (Organization organ : enterprise.getOrganizationList().getOrganizationList()) {
            if(organ instanceof HospitalAdminOrg && type == OrganizationType.HOSPITAL_ADMIN_ORG ){
               JOptionPane.showMessageDialog(null,"Hospital admin organization already exists","ERROR",JOptionPane.ERROR_MESSAGE);
                return;
            }
            else if(organ instanceof HospitalDoctorOrg && type == OrganizationType.HOSPITAL_DOCTOR_ORG ){
               JOptionPane.showMessageDialog(null,"Hospital doctor organization already exists","ERROR",JOptionPane.ERROR_MESSAGE);
                return;
            }
            else if( organ instanceof HouseholdOrg && type == OrganizationType.HOUSEHOLD_ORG){
                JOptionPane.showMessageDialog(null,"House organization already exists","ERROR",JOptionPane.ERROR_MESSAGE);
                return;
            }
            else if( organ instanceof EnergyResourceOrg && type == OrganizationType.ENERGY_RESOUCE_ORG){
                JOptionPane.showMessageDialog(null,"Energy organization already exists","ERROR",JOptionPane.ERROR_MESSAGE);
                return;
            }
             else if( organ instanceof GreenGasTrackingOrg && type == OrganizationType.GREEN_GAS_TRACKING_ORG){
                JOptionPane.showMessageDialog(null,"Greengas tracking organization already exists","ERROR",JOptionPane.ERROR_MESSAGE);
                return;
            }
             else if( organ instanceof PollutionBoardOrg && type == OrganizationType.POLLUTION_BOARD_ORG){
                JOptionPane.showMessageDialog(null,"Pollution board already exists","ERROR",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }    
        Organization org = enterprise.getOrganizationList().createAndAddOrg(type);
        populateTable();
    }//GEN-LAST:event_addOrgBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrgBtn;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox orgTypeComboBox;
    private javax.swing.JTable organizationTable;
    // End of variables declaration//GEN-END:variables
}
