/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.NeighborhoodAdmin;

import business.EcoDistrict;
import business.Enterprise.Enterprise;
import business.Neighborhood.Neighborhood;
import business.Organization.Organization;
import business.Person.Person;
import business.Role.EnterpriseAdmin;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reshmi
 */
public class ManageEnterpriseAccJPanel extends javax.swing.JPanel {

    /**
     * Creates new form mngEnterpriseAccJPanel
     */
    private JPanel userProcessContainer;
    private EcoDistrict ecoDistrict;
    private Neighborhood neighborhood;
    public ManageEnterpriseAccJPanel(JPanel userProcessContainer,EcoDistrict ecoDistrict,Neighborhood neighborhood) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoDistrict = ecoDistrict;
        this.neighborhood = neighborhood;
        populateTable();
        populateComboBox();
    }

    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel)enterpriseTable.getModel();

        model.setRowCount(0);
            for (Enterprise enterprise : neighborhood.getEnterpriseList().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccDir().getUserAccountList()) {
                    
                    Object[] row = new Object[3];
                    row[0] = enterprise.getOrgName();
                    row[1] = neighborhood.getNeighborhoodName();
                    row[2] = userAccount.getUsername();

                    model.addRow(row);
                }
            }  
    }
    
    public void populateComboBox()
    {
        areasComboBox.removeAllItems();
        areasComboBox.addItem(neighborhood);
    }
    
    public void populateEnterpriseComboBox(Neighborhood areas)
    {
        entComboBox.removeAllItems();
        
        for (Enterprise enterprise : areas.getEnterpriseList().getEnterpriseList()){
            entComboBox.addItem(enterprise);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseTable = new javax.swing.JTable();
        createEntBtn = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        entComboBox = new javax.swing.JComboBox();
        entAdminNameTxt = new javax.swing.JTextField();
        areasComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        entUserNameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        enterpriseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Neighborhood Name", "User Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseTable);

        createEntBtn.setBackground(new java.awt.Color(0, 153, 0));
        createEntBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        createEntBtn.setForeground(new java.awt.Color(255, 255, 255));
        createEntBtn.setText("CREATE");
        createEntBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEntBtnActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(0, 153, 0));
        backJButton.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create Enterprise Admin Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11), new java.awt.Color(102, 0, 102))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel2.setText("Enterprise Name");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel4.setText("User Name");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/DistrictAdminRole/admin1.png"))); // NOI18N

        entComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        areasComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        areasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areasComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel5.setText("Password");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel3.setText("Enterprise Admin");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setText("Neighborhood Area");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(entAdminNameTxt)
                    .addComponent(entUserNameTxt)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(entComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(areasComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(entComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entAdminNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entUserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(70, 70, 70)
                        .addComponent(createEntBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(createEntBtn))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void areasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areasComboBoxActionPerformed
        Neighborhood neighborhood = (Neighborhood) areasComboBox.getSelectedItem();
        if (neighborhood != null){
            populateEnterpriseComboBox(neighborhood);
        }
    }//GEN-LAST:event_areasComboBoxActionPerformed

    private void createEntBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEntBtnActionPerformed
        Enterprise enterprise = (Enterprise) entComboBox.getSelectedItem();
       
        String userName = entUserNameTxt.getText();
        String password = String.valueOf(passwordTxt.getPassword());
        String name = entAdminNameTxt.getText();
        if(userName.equals("")||password.equals("")||name.equals("")){
            JOptionPane.showMessageDialog(null, "Enter value in the fields!", "Empty Fields", JOptionPane.ERROR_MESSAGE);
        }
        else{
            for(Neighborhood area :ecoDistrict.getNeighborhoodList()){
                if(area!=null){
                    if(!area.getUserAccDir().checkIfUserNameIsUnique(userName)){
                        JOptionPane.showMessageDialog(this, "User Name Already Exists", "ERROR", JOptionPane.ERROR_MESSAGE);
                    return;
                    }
                
                    for (Enterprise entType : area.getEnterpriseList().getEnterpriseList()) {
                    if (entType != null) {
                        if (!entType.getUserAccDir().checkIfUserNameIsUnique(userName)) {
                            JOptionPane.showMessageDialog(this, "User Name Already Exists", "ERROR", JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                    for (Organization orgType : entType.getOrganizationList().getOrganizationList()) {
                    if (orgType != null) {
                        if (!orgType.getUserAccDir().checkIfUserNameIsUnique(userName)) {
                            JOptionPane.showMessageDialog(this, "User Name Already Exists", "ERROR", JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                    for (UserAccount UA : orgType.getUserAccDir().getUserAccountList()) {
                        if (UA.getUsername().equalsIgnoreCase(userName)) {
                            JOptionPane.showMessageDialog(this, "User Name Already Exists", "ERROR", JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                      }
                    }
                  }
                }
              }
            }
            }
            Person person = enterprise.getPersonDir().addPerson(name);
            UserAccount account = enterprise.getUserAccDir().createUserAccount(userName, password, person, new EnterpriseAdmin());
            JOptionPane.showMessageDialog(null, "new user account created", "New Account", JOptionPane.INFORMATION_MESSAGE);
        }

        entUserNameTxt.setText("");
        passwordTxt.setText("");
        populateTable();
    }//GEN-LAST:event_createEntBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox areasComboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createEntBtn;
    private javax.swing.JTextField entAdminNameTxt;
    private javax.swing.JComboBox entComboBox;
    private javax.swing.JTextField entUserNameTxt;
    private javax.swing.JTable enterpriseTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField passwordTxt;
    // End of variables declaration//GEN-END:variables
}
