/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.NeighborhoodAdmin;

import business.EcoDistrict;
import business.Enterprise.Enterprise;
import business.Neighborhood.Neighborhood;
import business.Organization.Organization;
import business.Organization.PollutionBoardOrg;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Reshmi
 */
public class NeighborhoodAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NeighborhoodAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoDistrict ecoDistrict;
    private Neighborhood neighborhood;
    private UserAccount account;
    private Enterprise enterprise;
    public NeighborhoodAdminWorkAreaJPanel(JPanel userProcessContainer,EcoDistrict ecoDistrict,Neighborhood neighborhood,
                                            UserAccount account,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoDistrict = ecoDistrict;
        this.neighborhood = neighborhood;
        this.account = account;
        this.enterprise = enterprise;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mngEnterprisesBtn = new javax.swing.JButton();
        mngEnterprisorAccBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mngAreaAlertsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        mngEnterprisesBtn.setBackground(new java.awt.Color(0, 153, 0));
        mngEnterprisesBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        mngEnterprisesBtn.setForeground(new java.awt.Color(255, 255, 255));
        mngEnterprisesBtn.setText("MANAGE ENTERPRISES");
        mngEnterprisesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngEnterprisesBtnActionPerformed(evt);
            }
        });

        mngEnterprisorAccBtn.setBackground(new java.awt.Color(0, 153, 0));
        mngEnterprisorAccBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        mngEnterprisorAccBtn.setForeground(new java.awt.Color(255, 255, 255));
        mngEnterprisorAccBtn.setText("MANAGE USER ACCOUNT");
        mngEnterprisorAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngEnterprisorAccBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/NeighborhoodAdmin/community_icons.png"))); // NOI18N

        mngAreaAlertsBtn.setBackground(new java.awt.Color(0, 153, 0));
        mngAreaAlertsBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        mngAreaAlertsBtn.setForeground(new java.awt.Color(255, 255, 255));
        mngAreaAlertsBtn.setText("MANAGE AREA ALERTS");
        mngAreaAlertsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngAreaAlertsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mngAreaAlertsBtn)
                    .addComponent(mngEnterprisorAccBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(mngEnterprisesBtn)))
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(mngEnterprisesBtn)
                .addGap(18, 18, 18)
                .addComponent(mngEnterprisorAccBtn)
                .addGap(18, 18, 18)
                .addComponent(mngAreaAlertsBtn)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mngEnterprisesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngEnterprisesBtnActionPerformed
        // TODO add your handling code here:
        ManageEnterprisesJPanel mngEntJPanel = new ManageEnterprisesJPanel(userProcessContainer, ecoDistrict,neighborhood);
        userProcessContainer.add("manageOrganizationJPanel", mngEntJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngEnterprisesBtnActionPerformed

    private void mngEnterprisorAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngEnterprisorAccBtnActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAccJPanel mngEntAccJPanel = new ManageEnterpriseAccJPanel(userProcessContainer, ecoDistrict,neighborhood);
        userProcessContainer.add("manageOrganizationJPanel", mngEntAccJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngEnterprisorAccBtnActionPerformed

    private void mngAreaAlertsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngAreaAlertsBtnActionPerformed
         Organization org = null;
         for(Enterprise ent:neighborhood.getEnterpriseList().getEnterpriseList()){
        for(Organization organization:ent.getOrganizationList().getOrganizationList()){
            if(organization instanceof PollutionBoardOrg){
                org = organization;
            }
        }
        }
        ManageAreaAlertsJPanel mngEntAccJPanel = new ManageAreaAlertsJPanel(userProcessContainer, ecoDistrict,neighborhood,account,(PollutionBoardOrg)org);
        userProcessContainer.add("manageOrganizationJPanel", mngEntAccJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngAreaAlertsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mngAreaAlertsBtn;
    private javax.swing.JButton mngEnterprisesBtn;
    private javax.swing.JButton mngEnterprisorAccBtn;
    // End of variables declaration//GEN-END:variables
}
