/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.EnergySourceBoardSupervisor;

import business.Enterprise.Enterprise;
import business.Organization.EnergyResourceOrg;
import business.Organization.HouseholdOrg;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userInterface.HospitalAdminRole.ManagePatientsJPanel;

/**
 *
 * @author Reshmi
 */
public class EnergySourceBoardAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnergySourceBoardAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EnergyResourceOrg energySourceOrg;
    private UserAccount userAccount;
    private Enterprise enterprise;
    public EnergySourceBoardAdminWorkAreaJPanel(JPanel userProcessContainer,Enterprise enterprise,EnergyResourceOrg energySourceOrg,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        //this.personDir = personDir;
        this.energySourceOrg = energySourceOrg;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mngEnergyConsumBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mngAreaAdminAlertsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        mngEnergyConsumBtn.setBackground(new java.awt.Color(0, 153, 0));
        mngEnergyConsumBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        mngEnergyConsumBtn.setForeground(new java.awt.Color(255, 255, 255));
        mngEnergyConsumBtn.setText("MANAGE ENERGY CONSUMPTION");
        mngEnergyConsumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngEnergyConsumBtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/EnergySourceBoardSupervisor/energy_efficiency_city.jpg"))); // NOI18N

        mngAreaAdminAlertsBtn.setBackground(new java.awt.Color(0, 153, 0));
        mngAreaAdminAlertsBtn.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        mngAreaAdminAlertsBtn.setForeground(new java.awt.Color(255, 255, 255));
        mngAreaAdminAlertsBtn.setText("MANAGE AREA ADMIN ALERTS");
        mngAreaAdminAlertsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngAreaAdminAlertsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mngEnergyConsumBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2))
                    .addComponent(mngAreaAdminAlertsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(mngEnergyConsumBtn)
                .addGap(18, 18, 18)
                .addComponent(mngAreaAdminAlertsBtn)
                .addGap(131, 131, 131))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mngEnergyConsumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngEnergyConsumBtnActionPerformed
        Organization org = null;
        for(Organization organization:enterprise.getOrganizationList().getOrganizationList()){
            if(organization instanceof HouseholdOrg){
                org = organization;
            }
        }
        ManageEnergyConsumptionsJPanel mngEnergyConsumJPanel = new ManageEnergyConsumptionsJPanel(userProcessContainer, (HouseholdOrg)org,userAccount,enterprise);
        userProcessContainer.add("ManageEnergyConsumptionsJPanel", mngEnergyConsumJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngEnergyConsumBtnActionPerformed

    private void mngAreaAdminAlertsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngAreaAdminAlertsBtnActionPerformed
        ManageAreaAdminAlertsJPanel mngAreaAdminAlertsJPanel = new ManageAreaAdminAlertsJPanel(userProcessContainer,userAccount,enterprise);
        userProcessContainer.add("mngAreaAdminAlertsJPanel", mngAreaAdminAlertsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngAreaAdminAlertsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mngAreaAdminAlertsBtn;
    private javax.swing.JButton mngEnergyConsumBtn;
    // End of variables declaration//GEN-END:variables
}
